-- Languages
INSERT [Localization].[Language] ([CultureName], [DisplayName], [Country], [Region], [IsDefaultLanguage]) VALUES (N'en-US', N'English - United States', N'English - United States', N'United States', 1)
INSERT [Localization].[Language] ([CultureName], [DisplayName], [Country], [Region], [IsDefaultLanguage]) VALUES (N'tr-TR', N'Turkish - Turkey', N'Turkish - Turkey', N'Turkey', 0)

--Test Project English Resources
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'AboutMe'		, N'AboutMe', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'Address'		, N'Address', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'City'			, N'City', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'Company'		, N'Company', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'ConfirmPassword', N'ConfirmPassword', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'Country'		, N'Country', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'EMailAddress'	, N'EMailAddress', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'FirstName'		, N'FirstName', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'LastName'		, N'LastName', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'Password'		, N'Password', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'PostalCode'		, N'PostalCode', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'Username'		, N'Username', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'BirthDate'		, N'Birth Date', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'Time'			, N'Time', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'Currency'		, N'Currency', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'PhoneNumber'	, N'Phone Number', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'CreditCard'		, N'CreditCard', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (1, N'IpAddress'		, N'IpAddress', NULL)

--Test Project Turkish Resources
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'AboutMe'		, N'Hakkımda', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'Address'		, N'Adres', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'City'			, N'Şehir', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'Company'		, N'Firma', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'ConfirmPassword', N'Şifre Onayı', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'Country'		, N'Ülke', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'EMailAddress'	, N'E-Posta Adresi', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'FirstName'		, N'Ad', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'LastName'		, N'Soyad', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'Password'		, N'Şifre', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'PostalCode'		, N'Posta Kodu', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'Username'		, N'Kullanıcı Adı', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'BirthDate'		, N'Doğum Tarihi', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'Time'			, N'Zaman', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'Currency'		, N'Para Birimi', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'PhoneNumber'	, N'Telefon Numarası', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'CreditCard'		, N'Kredi Kartı', NULL)
INSERT [Localization].[Resource] ([LanguageId], [Key], [Value], [Comment]) VALUES (2, N'IpAddress'		, N'İp Adresi', NULL)